import manifest from "../../public/tally-data/manifest.json";

import type { TallyDataManifest } from "./types";

// The manifest is generated by `pnpm sqlite:build` and written to
// `public/tally-data/manifest.json` (gitignored). It must exist at build time
// so this static import succeeds; bundling it into the route keeps the
// proxy edge-compatible with no filesystem read at runtime.
export const serverManifest = manifest as TallyDataManifest;
