/**
 * Type definitions for delegate data sourced from Tally (data/delegates.json).
 *
 * This is separate from the gov-tracker DelegateInfo type, which only
 * contains address + votingPower + lastChangeBlock from on-chain data.
 * TallyDelegate includes off-chain profile data (name, bio, statement).
 */

export interface TallyDelegateAccount {
  address: string;
  ens: string;
  name: string;
  bio: string;
  twitter: string;
  picture?: string | null;
}

export interface TallyDelegateStatement {
  statement: string;
  statementSummary: string;
  isSeekingDelegation: boolean;
}

export interface TallyDelegate {
  id: string;
  votesCount: string;
  delegatorsCount: number;
  isPrioritized: boolean;
  account: TallyDelegateAccount;
  statement: TallyDelegateStatement;
  labels: string[];
  delegateEligibility: unknown;
}

/**
 * Minimal delegate index entry for client-side use.
 * Generated by scripts/build-delegate-index.ts from delegates.json.
 */
export interface DelegateIndexEntry {
  name: string;
}

export type DelegateIndex = Record<string, DelegateIndexEntry>;
